### ISSUE TITLE
(5 SP) - As a user I want to be be abled to talk to the product and the product converts the speech to text

### ISSUE THREAD

**Issue by paul1610** [RezepProject/artifacts#52]

**Comment by fdornf** [comment]
1. Kompatibilität mit verschiedenen Versionen
	Man benötigt unbedingt Phython 3.6.x
2. Vortrainierte Language Models
	Auf der Seite von Deepspeech bin ich nur auf Englische LM's gestoßen, jedoch gibt es von 3. Anbietern auf GH (https://gitlab.com/Jaco-Assistant/deepspeech-polyglot) auch Lösungen auf Deutsch. Dies würde jedoch bedeuten, dass es notwendig ist, mehrere dieser Models zu nutzen.
3. Geschwindigkeit
	Es ist, zu meinem momentanen Informationsstand, nicht möglich die Gespräche auf jedem Gerät flüssig zu halten. Bei nur kurzen Sätzen, mit rund 10 Wörter, benötigt Deepspeech bis zu 4 Sekunden(CPU) oder 2,5 Sekunden(GPU). Um jedoch auf so kurze Zeiten zu kommen ist eine Nvidia Grafikkarte notwendig, welche ich nicht habe.
4. Lösungsvorschlag
	Google Cloud Dienst Speech

**Comment by fdornf** [comment]
DoD
    Speech Recognition Implemented: The product can effectively recognize speech.
    Conversion to Text: Speech is accurately converted to text.
    Accuracy: The accuracy of the speech-to-text conversion is above 90%.
    Performance: The conversion occurs with minimal delay.
    Error-Free: No critical bugs in the functionality.
